# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class T2stock < Formula
  desc "Real-time stock price tracker"
  homepage "https://github.com/franpfeiffer/homebrew-t2stock"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/franpfeiffer/t2stock/releases/download/v1.0.0/t2stock_1.0.0_darwin_amd64.tar.gz"
      sha256 "b58cdd29b12752557316ca6b554d8a02d9b6619a4342ab80e1a28209fe7d68be"

      def install
        bin.install "t2stock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/franpfeiffer/t2stock/releases/download/v1.0.0/t2stock_1.0.0_darwin_arm64.tar.gz"
      sha256 "ab6618135065b2c8caeb26a9c3232432d547089d9cb2c7808343586682234537"

      def install
        bin.install "t2stock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/franpfeiffer/t2stock/releases/download/v1.0.0/t2stock_1.0.0_linux_amd64.tar.gz"
      sha256 "18c5de65e473d31eb39070b6eb6ece1763782ddc06663b3df9f47c44bbe3d1d6"
      def install
        bin.install "t2stock"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/franpfeiffer/t2stock/releases/download/v1.0.0/t2stock_1.0.0_linux_armv6.tar.gz"
      sha256 "000acbdc9818a9dba07a0fb45db79490c2e67ef763856c9c4c3ddd46e2abcc9f"
      def install
        bin.install "t2stock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/franpfeiffer/t2stock/releases/download/v1.0.0/t2stock_1.0.0_linux_arm64.tar.gz"
      sha256 "34cf10435802a777f4df069df78c3f054d1b44b5735922430c278ec8b885098b"
      def install
        bin.install "t2stock"
      end
    end
  end
end
