# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class T2stock < Formula
  desc "Real-time stock price tracker"
  homepage "https://github.com/franpfeiffer/homebrew-t2stock/Formula"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/franpfeiffer/t2stock/releases/download/v1.0.3/t2stock_1.0.3_darwin_amd64.tar.gz"
      sha256 "ec4ec661008002ea4ee7b856c8804029f3a869925cdfb528baf5be11cd006e4c"

      def install
        bin.install "t2stock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/franpfeiffer/t2stock/releases/download/v1.0.3/t2stock_1.0.3_darwin_arm64.tar.gz"
      sha256 "c0adb337a5547e6a9862c1d372c7088c7e667adb631694e00162ede1a8c0463d"

      def install
        bin.install "t2stock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/franpfeiffer/t2stock/releases/download/v1.0.3/t2stock_1.0.3_linux_amd64.tar.gz"
      sha256 "a5fd95d6b4617b34aadda84df23e3c22fe4bb58cdb1d1552ab3170e35e7ea2cd"
      def install
        bin.install "t2stock"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/franpfeiffer/t2stock/releases/download/v1.0.3/t2stock_1.0.3_linux_armv6.tar.gz"
      sha256 "e201f22bbc044285fd0b6c5ef66c25e42e1327a7c8386f2bf09010d060298cfb"
      def install
        bin.install "t2stock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/franpfeiffer/t2stock/releases/download/v1.0.3/t2stock_1.0.3_linux_arm64.tar.gz"
      sha256 "1876a799c7b75413e99986237a61b503cd79bedbaa2744d0c1711f1c7d407b48"
      def install
        bin.install "t2stock"
      end
    end
  end
end
